export const countries = new Map<string, string>([
  ["Afghanistan", "🇺🇳"],
  ["Albania", "🇺🇳"],
  ["Algeria", "🇺🇳"],
  ["Andorra", "🇦🇩"],
  ["Antiguaand Barbuda", "🇺🇳"],
  ["Argentina", "🇦🇷"],
  ["Armenia", "🇺🇳"],
  ["Australia", "🇦🇺"],
  ["Austria", "🇦🇹"],
  ["Azerbaijan", "🇦🇿"],
  ["Bahamas", "🇺🇳"],
  ["Bahrain", "🇺🇳"],
  ["Bangladesh", "🇺🇳"],
  ["Barbados", "🇺🇳"],
  ["Belarus", "🇺🇳"],
  ["Belgium", "🇺🇳"],
  ["Belize", "🇺🇳"],
  ["Benin", "🇺🇳"],
  ["Bhutan", "🇺🇳"],
  ["Bolivia", "🇧🇴"],
  ["BosniaandHerzegovina", "🇺🇳"],
  ["Botswana", "🇺🇳"],
  ["Brazil", "🇧🇷"],
  ["Brunei", "🇺🇳"],
  ["Bulgaria", "🇺🇳"],
  ["BurkinaFaso", "🇺🇳"],
  ["Burundi", "🇺🇳"],
  ["Cabo Verde", "🇺🇳"],
  ["Cambodia", "🇺🇳"],
  ["Cameroon", "🇺🇳"],
  ["Canada", "🇺🇳"],
  ["Central African Republic", "🇺🇳"],
  ["Chad", "🇺🇳"],
  ["Chile", "🇨🇱"],
  ["China", "🇨🇳"],
  ["Colombia", "🇨🇴"],
  ["Comoros", "🇺🇳"],
  ["Congo", "🇺🇳"],
  ["CostaRica", "🇺🇳"],
  ["Croatia", "🇺🇳"],
  ["Cuba", "🇺🇳"],
  ["Cyprus", "🇺🇳"],
  ["Czechia", "🇺🇳"],
  ["Democratic Republic of the Congo", "🇺🇳"],
  ["Denmark", "🇺🇳"],
  ["Djibouti", "🇺🇳"],
  ["Dominica", "🇺🇳"],
  ["Dominican Republic", "🇩🇴"],
  ["Ecuador", "🇺🇳"],
  ["Egypt", "🇺🇳"],
  ["El Salvador", "🇺🇳"],
  ["Equatorial Guinea", "🇺🇳"],
  ["Eritrea", "🇺🇳"],
  ["Estonia", "🇺🇳"],
  ["Eswatini", "🇺🇳"],
  ["Ethiopia", "🇺🇳"],
  ["Fiji", "🇺🇳"],
  ["Finland", "🇺🇳"],
  ["France", "🇫🇷"],
  ["Gabon", "🇺🇳"],
  ["Gambia", "🇺🇳"],
  ["Georgia", "🇺🇳"],
  ["Germany", "🇩🇪"],
  ["Ghana", "🇺🇳"],
  ["Greece", "🇺🇳"],
  ["Grenada", "🇺🇳"],
  ["Guatemala", "🇺🇳"],
  ["Guinea", "🇺🇳"],
  ["Guinea", "🇺🇳"],
  ["Guyana", "🇺🇳"],
  ["Haiti", "🇺🇳"],
  ["Holy", "🇺🇳"],
  ["Honduras", "🇺🇳"],
  ["Hungary", "🇭🇺"],
  ["Iceland", "🇺🇳"],
  ["India", "🇺🇳"],
  ["Indonesia", "🇺🇳"],
  ["Iran", "🇺🇳"],
  ["Iraq", "🇺🇳"],
  ["Ireland", "🇮🇪"],
  ["Israel", "🇮🇱"],
  ["Italy", "🇮🇹"],
  ["Jamaica", "🇺🇳"],
  ["Japan", "🇯🇵"],
  ["Jordan", "🇺🇳"],
  ["Kazakhstan", "🇺🇳"],
  ["Kenya", "🇺🇳"],
  ["Kiribati", "🇺🇳"],
  ["Kuwait", "🇺🇳"],
  ["Kyrgyzstan", "🇺🇳"],
  ["Laos", "🇺🇳"],
  ["Latvia", "🇺🇳"],
  ["Lebanon", "🇺🇳"],
  ["Lesotho", "🇺🇳"],
  ["Liberia", "🇺🇳"],
  ["Libya", "🇺🇳"],
  ["Liechtenstein", "🇺🇳"],
  ["Lithuania", "🇺🇳"],
  ["Luxembourg", "🇺🇳"],
  ["Madagascar", "🇺🇳"],
  ["Malawi", "🇺🇳"],
  ["Malaysia", "🇺🇳"],
  ["Maldives", "🇺🇳"],
  ["Mali", "🇺🇳"],
  ["Malta", "🇺🇳"],
  ["Marshall Islands", "🇺🇳"],
  ["Mauritania", "🇺🇳"],
  ["Mauritius", "🇺🇳"],
  ["Mexico", "🇲🇽"],
  ["Micronesia", "🇺🇳"],
  ["Moldova", "🇺🇳"],
  ["Monaco", "🇺🇳"],
  ["Mongolia", "🇺🇳"],
  ["Montenegro", "🇺🇳"],
  ["Morocco", "🇺🇳"],
  ["Mozambique", "🇺🇳"],
  ["Myanmar", "🇺🇳"],
  ["Namibia", "🇺🇳"],
  ["Nauru", "🇺🇳"],
  ["Nepal", "🇺🇳"],
  ["Netherlands", "🇺🇳"],
  ["New Zealand", "🇺🇳"],
  ["Nicaragua", "🇺🇳"],
  ["Niger", "🇺🇳"],
  ["Nigeria", "🇳🇬"],
  ["NorthKorea", "🇺🇳"],
  ["NorthMacedonia", "🇺🇳"],
  ["Norway", "🇺🇳"],
  ["Oman", "🇺🇳"],
  ["Pakistan", "🇺🇳"],
  ["Palau", "🇺🇳"],
  ["Palestine State", "🇺🇳"],
  ["Panama", "🇵🇦"],
  ["Papua New Guinea", "🇺🇳"],
  ["Paraguay", "🇵🇾"],
  ["Peru", "🇵🇪"],
  ["Philippines", "🇵🇭"],
  ["Poland", "🇵🇱"],
  ["Portugal", "🇵🇹"],
  ["Qatar", "🇶🇦"],
  ["Romania", "🇷🇴"],
  ["Russia", "🇷🇺"],
  ["Rwanda", "🇺🇳"],
  ["Saint Kittsand Nevis", "🇺🇳"],
  ["SaintLucia", "🇺🇳"],
  ["Saint Vincent and the Grenadines", "🇺🇳"],
  ["Samoa", "🇺🇳"],
  ["San Marino", "🇸🇲"],
  ["Sao Tomeand Principe", "🇺🇳"],
  ["Saudi Arabia", "🇸🇦"],
  ["Senegal", "🇺🇳"],
  ["Serbia", "🇺🇳"],
  ["Seychelles", "🇺🇳"],
  ["SierraLeone", "🇺🇳"],
  ["Singapore", "🇸🇬"],
  ["Slovakia", "🇺🇳"],
  ["Slovenia", "🇺🇳"],
  ["SolomonIslands", "🇺🇳"],
  ["Somalia", "🇺🇳"],
  ["South Africa", "🇺🇳"],
  ["South Korea", "🇰🇷"],
  ["South Sudan", "🇺🇳"],
  ["Spain", "🇪🇸"],
  ["SriLanka", "🇺🇳"],
  ["Sudan", "🇺🇳"],
  ["Suriname", "🇺🇳"],
  ["Sweden", "🇸🇪"],
  ["Switzerland", "🇨🇭"],
  ["Syria", "🇺🇳"],
  ["Tajikistan", "🇺🇳"],
  ["Tanzania", "🇺🇳"],
  ["Thailand", "🇺🇳"],
  ["Timor", "🇺🇳"],
  ["Tonga", "🇺🇳"],
  ["TrinidadandTobago", "🇺🇳"],
  ["Tunisia", "🇺🇳"],
  ["Turkey", "🇹🇷"],
  ["Turkmenistan", "🇺🇳"],
  ["Tuvalu", "🇺🇳"],
  ["Uganda", "🇺🇳"],
  ["Ukraine", "🇺🇦"],
  ["United Arab Emirates", "🇺🇳"],
  ["United Kingdom", "🇬🇧"],
  ["USA", "🇺🇸"],
  ["Uruguay", "🇺🇳"],
  ["Uzbekistan", "🇺🇳"],
  ["Vanuatu", "🇺🇳"],
  ["Venezuela", "🇻🇪"],
  ["Vietnam", "🇺🇳"],
  ["Yemen", "🇺🇳"],
  ["Zambia", "🇺🇳"],
  ["Zimbabwe", "🇺🇳"],
]);
